services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    working_dir: /app/backend
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /app/frontend
    env_file:
      - frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  db_data: