services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    working_dir: app/backend
    env_file:
      - backend/.env
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: