"""fix: delete the slot model. 

Revision ID: 0024a6a8d119
Revises: ebac99e0cf9b
Create Date: 2025-06-12 06:55:45.669112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0024a6a8d119'
down_revision: Union[str, None] = 'ebac99e0cf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_table('slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parking_lot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_reserved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], name=op.f('slots_parking_lot_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('slots_pkey'))
    )
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    # ### end Alembic commands ###
