"""chore: include the duration hours and total cost in the reservation.

Revision ID: 21c13c669232
Revises: 26054b576540
Create Date: 2025-06-15 08:16:44.432376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c13c669232'
down_revision: Union[str, None] = '26054b576540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('duration_hours', sa.Float(), nullable=False))
    op.add_column('reservations', sa.Column('total_cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'total_cost')
    op.drop_column('reservations', 'duration_hours')
    # ### end Alembic commands ###
