"""chore: make the rate column not nullable.

Revision ID: 3322613f1a93
Revises: ea22d02f8146
Create Date: 2025-06-13 18:24:07.037127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3322613f1a93'
down_revision: Union[str, None] = 'ea22d02f8146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking_lots', 'rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking_lots', 'rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
