"""chore: remove the type and title.

Revision ID: 36aec5fc64de
Revises: 68671c3111eb
Create Date: 2025-06-16 08:09:50.195524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36aec5fc64de'
down_revision: Union[str, None] = '68671c3111eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
