"""chore: make the notified nullable.

Revision ID: b6f18114705e
Revises: 85644f365959
Create Date: 2025-06-16 06:08:53.753929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f18114705e'
down_revision: Union[str, None] = '85644f365959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'notified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'notified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
