"""feat: add type for notifications.

Revision ID: dc0bf8fa0245
Revises: b6f18114705e
Create Date: 2025-06-16 07:51:41.227036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0bf8fa0245'
down_revision: Union[str, None] = 'b6f18114705e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
