"""chore: make the column nullable first.

Revision ID: ea22d02f8146
Revises: d89deb9e9121
Create Date: 2025-06-13 18:22:50.963191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea22d02f8146'
down_revision: Union[str, None] = 'd89deb9e9121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_lots', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_lots', 'rate')
    # ### end Alembic commands ###
